# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "sources/", "/var/www/site", owner: "www-data", group: "www-data", create: true

  config.vm.define "cx11" do |cx11|
    cx11.vm.hostname = "cx11"
    cx11.vm.network "private_network", ip: "192.168.100.100"

    
    cx11.vm.provider "virtualbox" do |vb|
      vb.name = "cx11"
      vb.cpus = 1
      vb.memory = "2048"
    end
    
    cx11.vm.provision "shell", path: "scripts/u16_web_a.sh"

    cx11.vm.provision "file", source: "configs/apache.conf", destination: "/tmp/apache.conf"
    cx11.vm.provision "file", source: "other/info.php", destination: "/tmp/info.php"

    
    cx11.vm.provision "shell", inline: <<-SHELL
      mv /tmp/apache.conf /etc/apache2/sites-available/demo.conf
      mv /tmp/info.php /var/www/html/info.php
      a2enmod rewrite > /dev/null
      a2dissite 000-default.conf > /dev/null
      a2ensite demo.conf > /dev/null
      systemctl restart apache2 > /dev/null
    SHELL
  
    cx11.vm.provision "shell", path: "scripts/result.sh"
    
  end

end

