# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "sources/", "/var/www/site", owner: "www-data", group: "www-data", create: true

  config.vm.define "cx11" do |cx11|
    cx11.vm.hostname = "cx11"
    cx11.vm.network "private_network", ip: "192.168.100.100"

    
    cx11.vm.provider "virtualbox" do |vb|
      vb.name = "cx11"
      vb.cpus = 1
      vb.memory = "2048"
    end
    
    cx11.vm.provision "shell", path: "scripts/u16_web_n.sh"

    cx11.vm.provision "file", source: "configs/nginx.conf", destination: "/tmp/nginx.conf"
    cx11.vm.provision "file", source: "other/info.php", destination: "/tmp/info.php"

    cx11.vm.provision "shell", inline: <<-SHELL
      mv /tmp/nginx.conf /etc/nginx/sites-available/default
      mv /tmp/info.php /var/www/html/info.php
      systemctl reload nginx
    SHELL
  
    cx11.vm.provision "shell", path: "scripts/result.sh"

    
  end

end

